substitutions:
  name: apollo-plt-1b-aa01e0
  friendly_name: Apollo PLT-1B Hibiscus

packages:
  ApolloAutomation.PLT-1B: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1B.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: !secret api-key  #fZoaA12GUZJsNE0Zpems3ck+gJZzudaXw5TbdA8CPAo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
