esphome:
  name: apollo-h-1
  friendly_name: Apollo H-1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apollo-h-1-api-key   #"JzZXQ004qjfjvwLHF0QtjKy2w2ETKMhWrrf9T3A+2gw="

ota:
  - platform: esphome
    password: !secret apollo-h-1-ota-password    #  "d97191fb451cab99f70ace9f164a6906"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo-H-1 Fallback Hotspot"
    password: !secret api-key   #"seXBgiHdlNxC"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.187
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107

captive_portal:

packages:
  ApolloAutomation.H-1: # name of package/project
#    url: https://github.com/lcgreenwald/H-1 # url of the repository
    url: https://github.com/ApolloAutomation/H-1 # url of the repository
    ref: main # branch, tag or commit SHA
    files: [Integrations/ESPHome/H-1.yaml] # Path to config from base repo URL
    refresh: 0.25h # how often to sync updates from the remote url
  remote_package:
    url: https://github.com/lcgreenwald/H-1/
    ref: main
    files:
      - Integrations/ESPHome/MyTunes.yaml
    refresh: 0.1h
