substitutions:
  name: apollo-plt-1-b2c504
  friendly_name: Apollo PLT-1 Hibiscus
packages:
  ApolloAutomation.PLT-1: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: g/ROE/q4bH3/feSG5N/zHtlsEIWZIe38sywpFp7fw/g=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
