substitutions:
  name: esp32-devkit1
  version: "24.8.3.0"
  device_description: ${name} made by Larry Greenwald - version ${version}.

esphome:
  name: "${name}"
  friendly_name: ESP32-DevKit1
  comment: ESP32-DevKit1
  name_add_mac_suffix: False
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "LarryGreenwald.${name}"
    version: "${version}"

  min_version: 2024.6.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wMmO5gTZqzOIWPlUChxFJ02YDHn03VbuRDG2IU/6Sf4="

ota:
  - platform: esphome
    password: "1c71d2a5785eb9d3f21dc87141938281"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Devkit1 Fallback Hotspot"
    password: "9VM4BmHmWGu4"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.190
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:

safe_mode:

web_server:
  port: 80

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    