alias: "!Update Basement Freezer Temp Sensor"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.basement_freezer_temperature_sensor_online
    to: "on"
    from: "off"
conditions: []
actions:
  - if:
      - condition: state
        entity_id: update.basement_freezer_temperature_sensor_firmware_update
        state: "on"
    then:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.basement_freezer_temperature_sensor_prevent_sleep
      - data:
          message: Basement Freezer Temperature Sensor firmware updated.
          title: ESPHome Device Firmware Updated
        action: notify.notification_group_gavin
        enabled: true
      - action: update.install
        target:
          entity_id: update.basement_freezer_temperature_sensor_firmware_update
        data: {}
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - update.basement_freezer_temperature_sensor_firmware_update
            to: "off"
        timeout:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.basement_freezer_temperature_sensor_prevent_sleep
mode: single
