substitutions:
  name: apollo-plt-1b-aa01e0
  friendly_name: Apollo PLT-1B Garden1

packages:
  ApolloAutomation.PLT-1B:
    url: https://github.com/ApolloAutomation/PLT-1
#    url: https://github.com/lcgreenwald/PLT-1
    ref: main
    files: [Integrations/ESPHome/PLT-1B_Minimal.yaml]
    refresh: 1min

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: !secret plt-1b-garden1-api_key

#esp32:
#  framework:
#    type: esp-idf
#    version: 4.4.8
#    platform_version: 5.4.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.2.102
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107

