substitutions:
  name: apollo-air-1-b24ba4
  friendly_name: Apollo AIR-1 Greenhouse

packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
  remote_package:
    url: https://github.com/lcgreenwald/AIR-1/
    ref: main
    files:
      - Integrations/ESPHome/MyCustom.yaml
      - Integrations/ESPHome/InstantAQI.yaml
    refresh: 0d

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret air-1-greenhouse-api_key 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
