substitutions:
  name: apollo-air-1-b24ba4
  friendly_name: Apollo AIR-1 Greenhouse

packages:
  ApolloAutomation.AIR-1: # name of package/project
    url: https://github.com/ApolloAutomation/AIR-1 # url of the repository
#    url: https://github.com/lcgreenwald/AIR-1 # url of the repository
    ref: main # branch, tag or commit SHA
    files:
      - Integrations/ESPHome/AIR-1.yaml # Path to config from base repo URL
    refresh: 1d # how often to sync updates from the remote url
  remote_package:
    url: https://github.com/lcgreenwald/AIR-1/
    ref: main
    files:
      - Integrations/ESPHome/MyCustom.yaml
      - Integrations/ESPHome/InstantAQI.yaml
    refresh: 1min

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret air-1-greenhouse-api_key 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.2.101
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107


