#Define Project
substitutions:
  name: apollo-dev-1
  version:  "1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo DEV-1
  comment: Apollo DEV-1
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.DEV-1"
    version: "${version}"
 
# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
 
# Enable logging
logger:
 
# Enable Home Assistant API
api:
  encryption:
    key: !secret apollo-dev-1-api-key
#    key: "ayV16V/Ol7MgipryDPdCVI3VHCMsZIy7IzBUo3x2AMw="
 
ota:
  - platform: esphome
    password: !secret apollo-dev-1-ota-key
#    password: "a53d93acd493275512730c776f88722a"
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo-Dev-1 Fallback Hotspot"
    password: !secret wifi_password
 
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.190
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107

captive_portal:
 
web_server:
  port: 80
 
light:
  - platform: esp32_rmt_led_strip
    id: rgb_onboard_light
    name: "RGB Onboard Light"
    pin: GPIO8
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
    - addressable_rainbow:
    - pulse:
        name: "Slow Pulse"
        transition_length: 1000ms
        update_interval: 1000ms
        min_brightness: 50%
        max_brightness: 100%
    - pulse:
        name: "Fast Pulse"
        transition_length: 100ms
        update_interval: 100ms
        min_brightness: 50%
        max_brightness: 100%
  - platform: esp32_rmt_led_strip
    id: rgb_led_strip
    name: "RGB LED Strip"
    pin: GPIO10
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 30
    rgb_order: grb
    effects:
      - addressable_rainbow:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
 
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
 
sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature
 
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
 
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP"
      icon: "mdi:ip-outline"
