substitutions:
  version: "25.02.23.0"
  device_description: ${name} made by Larry Greenwald - version ${version}.


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
#  comment: ESP32 DevKit1
  name_add_mac_suffix: False
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "LarryGreenwald.${name}"
    version: "${version}"

  min_version: 2024.6.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: NONE
  
ota:
  - platform: esphome
    password: !secret ota_password
#    password: "1c71d2a5785eb9d3f21dc87141938281"


sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Light"
    pin: GPIO8
#    rmt_channel: 0
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 2
    rgb_order: grb
#    restore_mode: RESTORE_DEFAULT_ON
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 15%
          max_brightness: 40%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
#      - random:
#     - random:
#          name: Random Effect With Custom Values
#          transition_length: 5s
#          update_interval: 7s
#      - addressable_rainbow:
#      - addressable_rainbow:
#          name: Rainbow Effect With Custom Values
#          speed: 10
#          width: 50

text_sensor:
  - platform: wifi_info
    ip_address:
      name: " IP"
      icon: "mdi:ip-outline"
