substitutions:
  name: esp32-devkit1

packages:
  lcgreenwald.devkits: # name of package/project
    url: https://github.com/lcgreenwald/MyEsphome # url of the repository
    ref: dev # branch, tag or commit SHA
    files:
      - ESP32-devkits/esp32-devkit-core.yaml # Path to config from base repo URL
    refresh: 1min # how often to sync updates from the remote url

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: ESP32 DevKit1
  name_add_mac_suffix: False
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "LarryGreenwald.${name}"
    version: "${version}"

  min_version: 2024.6.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Devkit1 Fallback Hotspot"
    password: !secret ap_password

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.190
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107



